apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-app
  template:
    metadata:
      labels:
        app: kube-app
    spec:
      containers:
      - name: kube-app
        image: your-dockerhub-username/kube-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kube-app-service
spec:
  selector:
    app: kube-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
